# Generated by Django 3.1.3 on 2020-12-19 03:52

from django.db import migrations, models
import cabins.core.models._base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(cabins.core.models._base.SeriailizerMixin, models.Model),
        ),
    ]
