# Generated by Django 3.1.3 on 2020-12-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinscore', '0002_add_simple_image'),
        ('cabinspage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='description',
            field=models.TextField(default='Ipsum lorem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='basepage',
            name='og_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='basepage',
            name='og_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cabinscore.image'),
        ),
    ]
