# Generated by Django 3.1.3 on 2020-12-19 03:53

from django.db import migrations, models
import django.db.models.deletion
import cabins.core.models._base
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cabinspage', '0001_initial'),
        ('cabinscore', '0002_add_simple_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_content', models.TextField()),
                ('site_phone', models.CharField(max_length=16)),
                ('site_email', models.EmailField(max_length=255)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logo', to='cabinscore.image')),
                ('navigation', models.ManyToManyField(to='cabinspage.BasePage')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_content', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            bases=(cabins.core.models._base.SeriailizerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('site', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media', to='cabinsfront.sitecontent')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
