# Generated by Django 3.1.3 on 2020-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('cabinsfront', '0003_wagtailimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='navigation',
            field=models.ManyToManyField(to='wagtailcore.Page'),
        ),
    ]
