# Generated by Django 3.1.3 on 2020-12-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinsfront', '0004_addwagpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='site_email',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='site_phone',
        ),
    ]
