# Generated by Django 3.1.3 on 2020-12-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
    ]
