# Generated by Django 3.1.3 on 2020-12-22 00:54

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinspage', '0004_amenities'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cabinsback', '0004_add_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpage',
            name='activities',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='activities', through='cabinspage.Activities', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='food_drink',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='food_drink', through='cabinspage.FoodDrink', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='general',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='general', through='cabinspage.General', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='near_by_city',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='near_by_city', through='cabinspage.NearbyCity', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='near_by_water',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='near_by_water', through='cabinspage.NearByWater', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='open_dates',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='open_date', through='cabinspage.OpenDates', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='property_size',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='property_size', through='cabinspage.PropertySize', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='room',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='room', through='cabinspage.Room', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='services',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='services', through='cabinspage.Services', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='suitability',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='suitability', through='cabinspage.Suitability', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
