# Generated by Django 3.1.3 on 2020-12-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinsback', '0005_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpage',
            name='city',
            field=models.CharField(default='city', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingpage',
            name='country',
            field=models.CharField(default='country', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingpage',
            name='postal_code',
            field=models.CharField(default='00000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingpage',
            name='region',
            field=models.CharField(default='region', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingpage',
            name='street',
            field=models.CharField(default='street', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingpage',
            name='street2',
            field=models.CharField(default='street2', max_length=255),
            preserve_default=False,
        ),
    ]
