# Generated by Django 3.1.3 on 2020-12-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinsback', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpage',
            name='website',
            field=models.URLField(default='https://test.com'),
            preserve_default=False,
        ),
    ]
